name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (mac)
        if: runner.os == 'macOS'
        run: |
          brew update || true
          brew install gcc || true
      - name: Install dependencies (ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ build-essential
      - name: Run unit tests
        run: |
          chmod +x tests/run_tests.sh
          ./tests/run_tests.sh
